### ISSUE TITLE
Consider the format of files

### ISSUE THREAD

**Issue by LiangYuxuan** [TuringClass2016SCNU/Notes#1]
Markdown can provide the experience like PDF among some markdown viewer, and easier to modify. So using markdown as the format may be better than PDF.

**Comment by iosmanthus** [comment]
eh, I don't think you can see that a markdown file inserted mathematical  formulas are rendering well in Github. …

**Comment by OsmanthusTree** [comment]
eh, I don't think you can see that a markdown file inserted mathematical  formulas are rendering well in Github. …
